[project]
name = "webpage-summarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.5"
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "openai>=1.93.0",
    "requests>=2.32.4",
]
